name: Build to Netlify

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build to Netlify

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [24]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: npm run build

      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          install_command: "echo Skipping installing the dependencies"
          build_command: "echo Skipping building the web files"
          build_directory: "./dist"
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Deploy from GitHub Actions"
          NETLIFY_DEPLOY_TO_PROD: true

      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CROSS_REPO_UPDATE_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'LederCards',
              repo: 'Library',
              workflow_id: 'netlify.yml',
              ref: 'master'
            })
